name: CI

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      env:
        MIRROR_KEY: ${{ secrets.MIRROR_KEY }}
        MIRROR_CRT: ${{ secrets.MIRROR_CRT }}
      run: |
        mkdir rootCA
        mkdir official
        mkdir mirror
        
        cat ${MIRROR_KEY} > rootCA/mirror-adapter.key
        cat ${MIRROR_CRT} > rootCA/mirror-adapter.crt
        
        curl https://mirrors.tuna.tsinghua.edu.cn/jenkins/updates/update-center.json -o official/update-center.json
        
        docker run -v rootCA:/rootCA -v official:/official -v mirror:/mirror docker.pkg.github.com/jenkins-zh/mirror-adapter/mirror-adapter:0.0.1 -connection-check-url https://www.baidu.com/ \
        -mirror-json /mirror/update-center.json -mirror-url https://mirrors.tuna.tsinghua.edu.cn/jenkins/ \
        -official-json /official/update-center.json \
        -key /rootCA/mirror-adapter.key \
        -certificate /rootCA/mirror-adapter.crt \

